
services:
  app:
    build: .
    container_name: library-app
    ports:
      - "50111:50111"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/library
      SPRING_DATASOURCE_USERNAME: ${DB_LIBRARY_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_LIBRARY_PASSWORD}
    restart: always