spring:
  datasource:
    url: ${DB_LIBRARY_TEST_URL}
    username: ${DB_LIBRARY_TEST_USERNAME}
    password: ${DB_LIBRARY_TEST_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true