spring:
  application:
    name: library
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_LIBRARY_URL}
    username: ${DB_LIBRARY_USERNAME}
    password: ${DB_LIBRARY_PASSWORD}

server:
  port: 50111
  address: 0.0.0.0

logging:
  level:
    org:
      springframework:
#        security: DEBUG