CREATE TABLE book (
    id int generated by default as identity primary key,
    author_id int REFERENCES author(id),
    genre_id int REFERENCES genre(id),
    title varchar,
    year_published date
)