name: test + build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_LIBRARY_TEST_URL: ${{ secrets.DB_LIBRARY_TEST_URL }}
      DB_LIBRARY_TEST_USERNAME: ${{ secrets.DB_LIBRARY_TEST_USERNAME }}
      DB_LIBRARY_TEST_PASSWORD: ${{ secrets.DB_LIBRARY_TEST_PASSWORD }}
      DB_LIBRARY_URL: ${{ secrets.DB_LIBRARY_URL }}
      DB_LIBRARY_USERNAME: ${{ secrets.DB_LIBRARY_USERNAME }}
      DB_LIBRARY_PASSWORD: ${{ secrets.DB_LIBRARY_PASSWORD }}

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: library_test
          POSTGRES_USER: ${{ secrets.DB_LIBRARY_TEST_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_LIBRARY_TEST_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for postgres..."
            sleep 5
          done

      - name: Build and Test with Maven
        run: mvn clean test -Dspring.profiles.active=test